source 'https://gitee.com/jeelun/TestSpec.git'
source 'https://github.com/CocoaPods/Specs.git'


use_frameworks!

platform :ios, '8.0'

target 'JLTestUIKit_Example' do
  pod 'JLTestUIKit', :path => '../'

  target 'JLTestUIKit_Tests' do
    inherit! :search_paths

    
  end
end
